#!/usr/bin/env ruby

require 'simplecov'
require 'minitest/autorun'
require 'minitest/reporters'
SimpleCov.start do
  add_filter 'test'
end
require 'rubygems'
require_relative '../lib/tools'
Dir['./lib/lib/*.rb'].sort.each { |f| require f }

# Dir['./bin/*'].sort.each { |f| require f }

Minitest::Reporters.use! Minitest::Reporters::SpecReporter.new

here       = __dir__
mini_tests = Dir["#{here}/mini*.rb"]

if !ARGV.empty?

  files = []
  ARGV.each do |arq|
    file =  "#{here}/mini_#{arq}.rb"
    if mini_tests.include? file
      files << file
    else
      puts "Leave this parameter: File not found -> #{file}".light_red
    end
  end
  files.each do |file|
    require file
    puts file
  end

else
  Dir["#{here}/mini*.rb"].each do |file|
    require file
    puts file
  end
end

exit
