#!/usr/bin/env ruby
# coding: utf-8
require 'rubygems'
require 'tools'

args = ["1","2","3"]


ap args.extract_first.nil?
ap args.extract_first
ap args.extract_first
ap args.extract_first
ap args.extract_first.nil?


